### ISSUE TITLE
urllib2 Authentication seems to not work

### ISSUE THREAD

**Issue by ghost** [vicendominguez/wowza-zabbix-template#1]
Hi, thanks for the script and template. 

I ran into a problem, it seems that the getWowzaInfo script is not able to authenticate to the 'connectioncounts' and throws the following error:
urllib2.HTTPError: HTTP Error 401: Unauthorized

curl/wget with basic authentication to the same endpoint seem to work without problems.

**Comment by vicendominguez** [comment]
Are you using it inside of zabbix? are you using  it directly to the command line? What version of Zabbix are you using? Did you remember to create the macros? (Check the Install section in the README)

**Comment by ghost** [comment]
I'm running it from the same server I want to monitor and straight from the command line(Just to confirm that I get everything working before I import the template an link it). 

Is it possible it's not sending the correct Digest realm? 
I ran a simple script that checks the headers:

```
Access-Control-Expose-Headers: Date, Server, Content-Type, Content-Length
Cache-Control: no-cache
Server: WowzaStreamingEngine/4.4.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: OPTIONS, GET, POST, HEAD
WWW-Authenticate: Digest realm="Wowza Media Systems",  nonce="89d163082fa145999359252e58ca26f8", algorithm=MD5, qop="auth"
Connection: Keep-Alive
Access-Control-Allow-Headers: Content-Type, User-Agent, If-Modified-Since, Cache-Control, Range
Content-Type: text/html
Content-Length: 0

Digest realm="Wowza Media Systems",  nonce="89d163082fa145999359252e58ca26f8", algorithm=MD5, qop="auth"
```

(Zabbix is version 3)

**Comment by vicendominguez** [comment]
Hey Mihkel, yes... i think you are right. 

I am looking at your headers and the `algorithm=MD5`  digest looks like the issue. I wrote this monitor some years ago for the Wowza 3.x (base64) and Wowza4.4 looks like to be using a md5 hash now.

So sorry my friend but I am not working with Wowza Products.... but it would be a good idea to parse the digest and try to guess what is the algorithm and to reply with the correct answer.... I encourage to everyone to work in that line....

**Comment by ghost** [comment]
-edit-

Got it working, I replaced the auth/urlopen part with the following(+Realm variable)
        ```
authhandler = urllib2.HTTPDigestAuthHandler()
        authhandler.add_password(realm, url, username, password)
        opener = urllib2.build_opener(authhandler)
        urllib2.install_opener(opener)
        page_content = urllib2.urlopen(url)
        xmlroot = ET.fromstring(page_content.read())

```
```

**Comment by vicendominguez** [comment]
hehehe.... you're having a hard battle today!

This monitor is just the global stats per server. So we only need to look at the first part of the wowza3 xml to get the total of users  and, in the other side,to count the xml applications tree to get the number of applications up.

The key here is in the functions:

```
def getCurrentConnections():
        print xmlroot[0].text

def getCurrentStreams():
        Application =  xmlroot.findall('VHost/Application')
        print len(Application)
```

easy peace :)

**Comment by ghost** [comment]
Yeah, sorry, didnt dig deep and actually got it working now with the previous comment code i posted.

**Comment by vicendominguez** [comment]
Anyway, i figured out there are two forks of this repo with the digest solved. I don't know why those guys don't send me a PR..... :-1:

**Comment by vicendominguez** [comment]
Thx Mihkel. Welcome Wowza4! Solved in the PR https://github.com/vicendominguez/wowza-zabbix-template/pull/2
